platform :ios, '9.0'
use_frameworks!

target 'Demo' do

pod 'ModelMapper', :git => 'https://github.com/lyft/mapper.git', :tag => '5.0.0-beta.2'
pod 'Moya-ModelMapper', :path => "../"

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
